---
- name: Test connection with instance and install Nginx
  hosts: all
  become: True
  tasks:
    - name: Ensure Nginx is installed
      apt:
        name: nginx
        state: present
        update_cache: yes
    - name: start and enable Nginx service
      service:
        name: nginx
        state: started
        enabled: yes